### ISSUE TITLE
Wrong block positioning algorithm

### ISSUE THREAD

**Issue by daniele-athome** [daniele-athome/jsPlumbTree#1]
Some blocks are drawn in a wrong position, specificallty the vertical margin between certain blocks is smaller than it should be.

**Comment by gpalleschi** [comment]
If I enter in a created node and save with or without doing modification this is te result :
![image](https://user-images.githubusercontent.com/12493269/79586298-35f52580-80d1-11ea-8135-ab79ea1569ce.png)

**Comment by gpalleschi** [comment]
This issue is only on the last node :

![image](https://user-images.githubusercontent.com/12493269/79587912-84a3bf00-80d3-11ea-9345-c7613fab5726.png)

**Comment by gpalleschi** [comment]
[issuetree.txt](https://github.com/daniele-athome/jsPlumbTree/files/4493892/issuetree.txt)

**Comment by gpalleschi** [comment]
![image](https://user-images.githubusercontent.com/12493269/79588678-9174e280-80d4-11ea-92b9-5219ddb99b06.png)

**Comment by gpalleschi** [comment]
This is in the second branch
![image](https://user-images.githubusercontent.com/12493269/79588861-d731ab00-80d4-11ea-83a1-c7bd3fe00a8e.png)
